name: 👷 Pull Requset CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  ready_to_review:
    if: always()
    needs: check
    uses: ./.github/workflows/readyToReview.yml
    secrets: inherit
    with:
      has_failure: ${{ needs.check.result == 'failure' }}
